# Generated by Django 5.0.2 on 2024-03-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_backgroundimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundImage',
        ),
    ]
